### ISSUE TITLE
Need clear acceptable license for TESample

### ISSUE THREAD

**Issue by agoode** [jcreedcmu/twelf-mac#17]
The sample code is old and just says "Copyright (C) 1989 Apple Computer, Inc. All rights reserved."

It is still available from Apple: https://developer.apple.com/library/archive/samplecode/TESample/Introduction/Intro.html

Therefore, I would like to claim that this is "Sample Code" and is covered by https://developer.apple.com/support/downloads/terms/apple-sample-code/Apple-Sample-Code-License.pdf, so this is probably fine.

But there may be changes from https://github.com/CamHenlin/TESample that are not under a clear license. It would be good to know what changes there were.

This is to ensure compliance with https://opensource.google/documentation/reference/patching for me.

**Comment by jcreedcmu** [comment]
I've reached out via email to the author @CamHenlin of https://github.com/CamHenlin/TESample and await a response

**Comment by jcreedcmu** [comment]
He says he's travelling at the moment but will follow up in a few days.

**Comment by jcreedcmu** [comment]
Does https://github.com/CamHenlin/TESample/blob/main/LICENSE take care of this then?

**Comment by agoode** [comment]
Assuming Cam's changes are equally licensed.

**Comment by jcreedcmu** [comment]
Confirmed by email, he said:

> Yes, I did very little to that repo, essentially just enough to get it compiling with Retro68. So felt like it was appropriate to leave Apple's license to cover the changes
