### ISSUE TITLE
Implement Finder Icon Help Resource

### ISSUE THREAD

**Issue by agoode** [jcreedcmu/twelf-mac#31]
Something like
<img width="221" alt="Screenshot 2024-04-22 at 15 24 40" src="https://github.com/jcreedcmu/twelf-mac/assets/59842/6309d13a-721e-42ce-a89c-d08b216dc989">

https://dev.os9.ca/techpubs/mac/MoreToolbox/MoreToolbox-199.html#HEADING199-0

**Comment by jcreedcmu** [comment]
Oh I didn't know this was a feature, great idea.
