### ISSUE TITLE
Hyphen is not the same as en dash

### ISSUE THREAD

**Issue by tom7** [jcreedcmu/twelf-mac#33]
Only an ASCIIphile would think these are the same thing. Or a child

**Comment by jcreedcmu** [comment]
Before: [hypen-minus, unbalanced, awkward, repulsive]
![image](https://github.com/jcreedcmu/twelf-mac/assets/1500822/2f9a7c38-53b7-4618-9bca-6855abbda9a7)

After: [en-dash, balanced, elegant, inviting]
![image](https://github.com/jcreedcmu/twelf-mac/assets/1500822/a3565ebe-5674-4371-9cf0-f7d5664c3329)

**Comment by agoode** [comment]
It is as a thorn has been removed from my eye
